# Generated by Django 4.2.1 on 2023-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
